### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by snafus** [snafus/xrdreport#1]
```
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: Traceback (most recent call last):
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: self.finish_request(request, client_address)
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: self.RequestHandlerClass(request, client_address, self)
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib/python3.6/site-packages/xrdreporter/requestHandlers.py", line 109, in __init__
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: super().__init__(*args,**kwargs)
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: self.handle()
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib/python3.6/site-packages/xrdreporter/requestHandlers.py", line 158, in handle
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: stats = augment_raltier1(stats)
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: File "/usr/lib/python3.6/site-packages/xrdreporter/requestHandlers.py", line 73, in augment_raltier1
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: if 'nubes' in host:
Sep 22 23:50:13 host-172-16-105-194.nubes.stfc.ac.uk xrdrep.py[17171]: TypeError: argument of type 'int' is not iterable
```

**Comment by snafus** [comment]
Protection added in 
https://github.com/snafus/xrdreport/pull/2
